instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: jenkins-master
    properties:
      jenkins:
        admin:
          email: buildtools@finkit.com
          password: ((jenkins_admin_password))
        agent:
          password: ((jenkins_agent_password))
        config: config.xml
        github:
          oauth:
            admins:
              admin1: ((jenkins_oauth_admin_user_1))
              admin2: ((jenkins_oauth_admin_user_2))
              admin3: ((jenkins_oauth_admin_user_3))
            client:
              id: ((jenkins_oauth_clientID))
              secret: ((jenkins_oauth_clientSecret))
            org_name: ((github_oauth_org_name))
            url:
              api: ((jenkins_oauth_github_api_ui))
              web: ((jenkins_oauth_github_web_ui))
        server:
          address: ((jenkins_server_url))
    release: devtools
  name: jenkins-master
  networks:
  - name: default
  persistent_disk_pool: 100GB
  stemcell: default
  vm_extensions:
  - internet-required
  - jenkins-pool
  vm_type: default
- azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: jenkins-slave
    properties:
      jenkins:
        slave:
          executors: 2
          labels: build
          master_password: ((jenkins_agent_password))
          master_username: agent
          mode: exclusive
    release: devtools
  name: jenkins-slave
  networks:
  - name: default
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: nexus
    properties:
      nexus:
        admin:
          password: ((nexus_admin_password))
        deployer:
          password: ((nexus_deployer_password))
    release: devtools
  name: nexus
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - internet-required
  - nexus-pool
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: sonarqube
    properties:
    release: devtools
  name: sonarqube
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - internet-required
  - sonar-pool
  vm_type: default
name: buildstack
os: ubuntu-trusty
releases:
- name: devtools
  sha1: 7d3e25d565253d27462648684c5118e38f09afb5
  url: https://github.com/finkit/devtools-boshrelease/releases/download/v2.0.36/devtools-boshrelease-v2.0.36.tgz
  version: 2.0.36
- name: newrelic-infra-bosh
  sha1: 5be785540118f1b3fab909ba30f64b30e48f76a5
  url: https://github.com/dazjones/newrelic-infra-bosh/releases/download/v0.1.2/newrelic-infra-bosh-0.1.2.tgz
  version: 0.1.2
- name: stackdriver-tools
  sha1: 9785cd55b7b15df43ffe890ab66b398634e6e841
  url: https://github.com/cloudfoundry-community/stackdriver-tools/releases/download/v2.0.1/stackdriver-tools-2.0.1.tgz
  version: 2.0.1
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3541.12"
update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000
variables:
- name: jenkins_admin_password
  type: password
- name: jenkins_agent_password
  type: password
- name: nexus_admin_password
  type: password
- name: nexus_deployer_password
  type: password

