instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: jenkins-master
    properties:
      jenkins:
        admin:
          email: buildtools@finkit.com
          password: ((jenkins_admin_password))
        agent:
          password: ((jenkins_agent_password))
        server:
          address: ((jenkins_server_url))
    release: jenkins
  name: jenkins-master
  networks:
  - name: default
  persistent_disk_pool: 100GB
  stemcell: default
  vm_extensions:
  - internet-required
  - jenkins-pool
  vm_type: default
- azs:
  - z1
  - z2
  instances: 2
  jobs:
  - name: docker
    properties:
      tcp_address: 0.0.0.0
      tls_cacert: ((docker-tls.ca))
      tls_cert: ((docker-tls.certificate))
      tls_key: ((docker-tls.private_key))
    release: docker
  - name: jenkins-slave
    properties:
      jenkins:
        slave:
          executors: 2
          labels: build
          master_password: ((jenkins_agent_password))
          master_username: agent
          mode: exclusive
          type: build
    release: jenkins
  name: jenkins-slave
  networks:
  - name: default
  persistent_disk_pool: 10GB
  stemcell: default
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: nexus
    properties:
      nexus:
        admin:
          password: ((nexus_admin_password))
        deployer:
          password: ((nexus_deployer_password))
        developer:
          password: ((nexus_developer_password))
    release: nexus
  name: nexus
  networks:
  - name: default
  persistent_disk_pool: 500GB
  stemcell: default
  vm_extensions:
  - internet-required
  - nexus-pool
  vm_type: default
- azs:
  - z1
  instances: 1
  jobs:
  - name: sonarqube
    properties:
      sonar:
        admin:
          password: ((sonar_admin_password))
    release: sonarqube
  name: sonarqube
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - internet-required
  - sonar-pool
  vm_type: default
name: buildstack
os: ubuntu-trusty
releases:
- name: jenkins
  sha1: 64312a80c08bca9d67ed729754c6cfc6cf9c8c79
  url: https://storage.googleapis.com/buildtools-release-tarballs/jenkins-boshrelease/jenkins-boshrelease-v0.0.71.tgz
  version: 0.0.71
- name: nexus
  sha1: 1658e6f386ad8543c6440aa3b99afff7de47908e
  url: https://storage.googleapis.com/buildtools-release-tarballs/nexus-boshrelease/nexus-boshrelease-v1.0.10.tgz
  version: 1.0.10
- name: sonarqube
  sha1: 2921f3d0df358ce180ba60bd97d743ac357367c7
  url: https://storage.googleapis.com/buildtools-release-tarballs/sonarqube-boshrelease/sonarqube-boshrelease-v0.0.41.tgz
  version: 0.0.41
- name: docker
  sha1: f192296243e68150ae66656fc9134a2b2a023184
  url: https://github.com/cloudfoundry-incubator/docker-boshrelease/releases/download/v32.0.0/docker-32.0.0.tgz
  version: 32.0.0
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3586.26"
update:
  canaries: 1
  canary_watch_time: 15000-300000
  max_in_flight: 1
  update_watch_time: 15000-300000
variables:
- name: docker-ca
  options:
    common_name: dockerCA
    is_ca: true
  type: certificate
- name: docker-tls
  options:
    ca: docker-ca
    common_name: docker
    extended_key_usage:
    - client_auth
  type: certificate
- name: jenkins_admin_password
  type: password
- name: jenkins_agent_password
  type: password
- name: nexus_admin_password
  type: password
- name: nexus_deployer_password
  type: password
- name: nexus_developer_password
  type: password
- name: sonar_admin_password
  type: password
- name: sonar_mysql_password
  type: password

